/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as QueryRouteImport } from './routes/query'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as ApiDocRouteImport } from './routes/api/doc'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiPhotoRouteImport } from './routes/api/photo'
import { Route as ApiPhotoFileRouteImport } from './routes/api/photo-file'
import { Route as ApiPhotoFlagsRouteImport } from './routes/api/photo-flags'
import { Route as ApiPhotoScanRouteImport } from './routes/api/photo-scan'
import { Route as ApiUpdateRouteImport } from './routes/api/update'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiVolcanoChatRouteRouteImport } from './routes/api/volcano-chat-route'
import { Route as ApiVolcanoHealthRouteImport } from './routes/api/volcano-health'
import { Route as ApiYearRouteImport } from './routes/api/year'
import { Route as ApiFileKindRouteImport } from './routes/api/file/$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocRoute = ApiDocRouteImport.update({
  id: '/api/doc',
  path: '/api/doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoRoute = ApiPhotoRouteImport.update({
  id: '/api/photo',
  path: '/api/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoFileRoute = ApiPhotoFileRouteImport.update({
  id: '/api/photo-file',
  path: '/api/photo-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoFlagsRoute = ApiPhotoFlagsRouteImport.update({
  id: '/api/photo-flags',
  path: '/api/photo-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoScanRoute = ApiPhotoScanRouteImport.update({
  id: '/api/photo-scan',
  path: '/api/photo-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateRoute = ApiUpdateRouteImport.update({
  id: '/api/update',
  path: '/api/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVolcanoChatRouteRoute = ApiVolcanoChatRouteRouteImport.update({
  id: '/api/volcano-chat-route',
  path: '/api/volcano-chat-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVolcanoHealthRoute = ApiVolcanoHealthRouteImport.update({
  id: '/api/volcano-health',
  path: '/api/volcano-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYearRoute = ApiYearRouteImport.update({
  id: '/api/year',
  path: '/api/year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileKindRoute = ApiFileKindRouteImport.update({
  id: '/api/file/$kind',
  path: '/api/file/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/import': typeof ImportRoute
  '/payments': typeof PaymentsRoute
  '/people': typeof PeopleRoute
  '/photos': typeof PhotosRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/doc': typeof ApiDocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/photo-file': typeof ApiPhotoFileRoute
  '/api/photo-flags': typeof ApiPhotoFlagsRoute
  '/api/photo-scan': typeof ApiPhotoScanRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/version': typeof ApiVersionRoute
  '/api/volcano-chat-route': typeof ApiVolcanoChatRouteRoute
  '/api/volcano-health': typeof ApiVolcanoHealthRoute
  '/api/year': typeof ApiYearRoute
  '/api/file/$kind': typeof ApiFileKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/import': typeof ImportRoute
  '/payments': typeof PaymentsRoute
  '/people': typeof PeopleRoute
  '/photos': typeof PhotosRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/doc': typeof ApiDocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/photo-file': typeof ApiPhotoFileRoute
  '/api/photo-flags': typeof ApiPhotoFlagsRoute
  '/api/photo-scan': typeof ApiPhotoScanRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/version': typeof ApiVersionRoute
  '/api/volcano-chat-route': typeof ApiVolcanoChatRouteRoute
  '/api/volcano-health': typeof ApiVolcanoHealthRoute
  '/api/year': typeof ApiYearRoute
  '/api/file/$kind': typeof ApiFileKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/expenses': typeof ExpensesRoute
  '/files': typeof FilesRoute
  '/import': typeof ImportRoute
  '/payments': typeof PaymentsRoute
  '/people': typeof PeopleRoute
  '/photos': typeof PhotosRoute
  '/query': typeof QueryRoute
  '/settings': typeof SettingsRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/doc': typeof ApiDocRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/photo': typeof ApiPhotoRoute
  '/api/photo-file': typeof ApiPhotoFileRoute
  '/api/photo-flags': typeof ApiPhotoFlagsRoute
  '/api/photo-scan': typeof ApiPhotoScanRoute
  '/api/update': typeof ApiUpdateRoute
  '/api/version': typeof ApiVersionRoute
  '/api/volcano-chat-route': typeof ApiVolcanoChatRouteRoute
  '/api/volcano-health': typeof ApiVolcanoHealthRoute
  '/api/year': typeof ApiYearRoute
  '/api/file/$kind': typeof ApiFileKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/audit'
    | '/contracts'
    | '/expenses'
    | '/files'
    | '/import'
    | '/payments'
    | '/people'
    | '/photos'
    | '/query'
    | '/settings'
    | '/api/audit'
    | '/api/auth'
    | '/api/backup'
    | '/api/doc'
    | '/api/health'
    | '/api/ledger'
    | '/api/photo'
    | '/api/photo-file'
    | '/api/photo-flags'
    | '/api/photo-scan'
    | '/api/update'
    | '/api/version'
    | '/api/volcano-chat-route'
    | '/api/volcano-health'
    | '/api/year'
    | '/api/file/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/audit'
    | '/contracts'
    | '/expenses'
    | '/files'
    | '/import'
    | '/payments'
    | '/people'
    | '/photos'
    | '/query'
    | '/settings'
    | '/api/audit'
    | '/api/auth'
    | '/api/backup'
    | '/api/doc'
    | '/api/health'
    | '/api/ledger'
    | '/api/photo'
    | '/api/photo-file'
    | '/api/photo-flags'
    | '/api/photo-scan'
    | '/api/update'
    | '/api/version'
    | '/api/volcano-chat-route'
    | '/api/volcano-health'
    | '/api/year'
    | '/api/file/$kind'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/audit'
    | '/contracts'
    | '/expenses'
    | '/files'
    | '/import'
    | '/payments'
    | '/people'
    | '/photos'
    | '/query'
    | '/settings'
    | '/api/audit'
    | '/api/auth'
    | '/api/backup'
    | '/api/doc'
    | '/api/health'
    | '/api/ledger'
    | '/api/photo'
    | '/api/photo-file'
    | '/api/photo-flags'
    | '/api/photo-scan'
    | '/api/update'
    | '/api/version'
    | '/api/volcano-chat-route'
    | '/api/volcano-health'
    | '/api/year'
    | '/api/file/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  ContractsRoute: typeof ContractsRoute
  ExpensesRoute: typeof ExpensesRoute
  FilesRoute: typeof FilesRoute
  ImportRoute: typeof ImportRoute
  PaymentsRoute: typeof PaymentsRoute
  PeopleRoute: typeof PeopleRoute
  PhotosRoute: typeof PhotosRoute
  QueryRoute: typeof QueryRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiBackupRoute: typeof ApiBackupRoute
  ApiDocRoute: typeof ApiDocRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiPhotoRoute: typeof ApiPhotoRoute
  ApiPhotoFileRoute: typeof ApiPhotoFileRoute
  ApiPhotoFlagsRoute: typeof ApiPhotoFlagsRoute
  ApiPhotoScanRoute: typeof ApiPhotoScanRoute
  ApiUpdateRoute: typeof ApiUpdateRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiVolcanoChatRouteRoute: typeof ApiVolcanoChatRouteRoute
  ApiVolcanoHealthRoute: typeof ApiVolcanoHealthRoute
  ApiYearRoute: typeof ApiYearRoute
  ApiFileKindRoute: typeof ApiFileKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc': {
      id: '/api/doc'
      path: '/api/doc'
      fullPath: '/api/doc'
      preLoaderRoute: typeof ApiDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo': {
      id: '/api/photo'
      path: '/api/photo'
      fullPath: '/api/photo'
      preLoaderRoute: typeof ApiPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo-file': {
      id: '/api/photo-file'
      path: '/api/photo-file'
      fullPath: '/api/photo-file'
      preLoaderRoute: typeof ApiPhotoFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo-flags': {
      id: '/api/photo-flags'
      path: '/api/photo-flags'
      fullPath: '/api/photo-flags'
      preLoaderRoute: typeof ApiPhotoFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo-scan': {
      id: '/api/photo-scan'
      path: '/api/photo-scan'
      fullPath: '/api/photo-scan'
      preLoaderRoute: typeof ApiPhotoScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update': {
      id: '/api/update'
      path: '/api/update'
      fullPath: '/api/update'
      preLoaderRoute: typeof ApiUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/volcano-chat-route': {
      id: '/api/volcano-chat-route'
      path: '/api/volcano-chat-route'
      fullPath: '/api/volcano-chat-route'
      preLoaderRoute: typeof ApiVolcanoChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/volcano-health': {
      id: '/api/volcano-health'
      path: '/api/volcano-health'
      fullPath: '/api/volcano-health'
      preLoaderRoute: typeof ApiVolcanoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/year': {
      id: '/api/year'
      path: '/api/year'
      fullPath: '/api/year'
      preLoaderRoute: typeof ApiYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$kind': {
      id: '/api/file/$kind'
      path: '/api/file/$kind'
      fullPath: '/api/file/$kind'
      preLoaderRoute: typeof ApiFileKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  ContractsRoute: ContractsRoute,
  ExpensesRoute: ExpensesRoute,
  FilesRoute: FilesRoute,
  ImportRoute: ImportRoute,
  PaymentsRoute: PaymentsRoute,
  PeopleRoute: PeopleRoute,
  PhotosRoute: PhotosRoute,
  QueryRoute: QueryRoute,
  SettingsRoute: SettingsRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiBackupRoute: ApiBackupRoute,
  ApiDocRoute: ApiDocRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiPhotoRoute: ApiPhotoRoute,
  ApiPhotoFileRoute: ApiPhotoFileRoute,
  ApiPhotoFlagsRoute: ApiPhotoFlagsRoute,
  ApiPhotoScanRoute: ApiPhotoScanRoute,
  ApiUpdateRoute: ApiUpdateRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiVolcanoChatRouteRoute: ApiVolcanoChatRouteRoute,
  ApiVolcanoHealthRoute: ApiVolcanoHealthRoute,
  ApiYearRoute: ApiYearRoute,
  ApiFileKindRoute: ApiFileKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
